### ISSUE TITLE
AttributeError while running sample.py: 'torch.distributed' has no attribute 'ReduceOp'

### ISSUE THREAD

**Issue by Ftuuky** [openai/jukebox#21] opened 2020-05-01 16:17 UTC
Following up the readme.md instructions and when trying to run sample.py I get the following error:

Traceback (most recent call last):
  File "jukebox/sample.py", line 7, in <module>
    from jukebox.utils.audio_utils import save_wav, load_audio
  File "c:\windows\system32\jukebox\jukebox\utils\audio_utils.py", line 6, in <module>
    from jukebox.utils.dist_utils import print_once
  File "c:\windows\system32\jukebox\jukebox\utils\dist_utils.py", line 22, in <module>
    def allreduce(x, op=dist.ReduceOp.SUM):
AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'

OS: Windows10

**Comment by gnhdnb** [comment] 2020-05-01 21:15
torch.distributed does not support windows. You have to run it on linux or try to work your way around by replacing all dist.* calls by stubs.

**Comment by prafullasd** [comment] 2020-05-05 22:52
Closing as duplicate of #36

**Closed by prafullasd** 2020-05-05 22:52 UTC
